### ISSUE TITLE
💡 [FEAT] Discord Integration

### ISSUE THREAD

**Issue by ghost** [kraanzu/smassh#16]
Monkeytype has an option to connect to Discord, where the server members get a specific role according to their speed. For example, if a user has a 63 WPM, they get a 60-69 role. It would be awesome if this was to be implemented in termtyper, since you have a discord server :)

I will be glad to open up a PR for this

**Comment by VoidCupboard** [comment]
Actually I have started working on this pr myself, but thanks for your concern

**Comment by kraanzu** [comment]
Thanks @stautonico, but as @VoidCupboard asked for this first.. I'll be assigning this to him.
If, however for some reason, he backs out...I'll be more than happy to help you with the PR :)
