### ISSUE TITLE
I'm not very good at python. What errors have I encountered and how should I run it

### ISSUE THREAD

**Issue by DearZack** [kraanzu/smassh#25]
I'm not very good at python. What errors have I encountered and how should I run it

**Comment by DearZack** [comment]
![Snipaste_2022-07-20_12-31-45](https://user-images.githubusercontent.com/17618134/179897577-f700d909-a891-4639-b3cb-d43a6aa496a7.jpg)

**Comment by Maou-Shimazu** [comment]
It's the location of where the package was installed. You want to go ahead and add 
```
C:\Users\<name>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\Scripts
``` 
in your PATH. After that is done it should run with just `termtyper` in your terminal.

[How you can add something to path on windows](https://www.architectryan.com/2018/03/17/add-to-the-path-on-windows-10/)

**Comment by kraanzu** [comment]
Closing as stale. Feel free to re-open if there are any further issues
