### ISSUE TITLE
No click sound and can't use underline caret style in Windows Terminal [BUG]

### ISSUE THREAD

**Issue by bickman** [kraanzu/smassh#38]
OS: Windows 11
Terminal: Windows Terminal
Shell: Power shell
Python Version: 3.10
Issue: No sound when typing, I have set keypress sound on, and no underline  caret sytle.
I tested in cmd ,still no sound but underline caret display normally.
Feature request: Normal vertical line caret style and it is better for typing.

**Comment by kraanzu** [comment]
>  Feature request: Normal vertical line caret style and it is better for typing.

Yes that would be great but I'm afraid that I would have to use the pipe symbol ( `|` ) as alternate for the cursor which will cause distraction while typing so I chose to avoid it

> No sound when typing, I have set key-press sound on, and no underline caret style.

Hmm...that's strange. Can you hear the sound when moving through the main menu?

**Comment by bickman** [comment]
> Hmm...that's strange. Can you hear the sound when moving through the main menu?
No, I can't hear any sound in the main menu too

**Comment by somenothing** [comment]
> No, I can't hear any sound in the main menu too

Did you use the exe files in Actions? Those files don't contain audio files and I'm working on it.

I can't hear anything while typing either. I don't know if this is not accomplished or if there is a bug.

**Comment by bickman** [comment]
> Did you use the exe files in Actions?

Yes, I have used the exe file, seems working as same as in the cmd, no sound either.

**Comment by kraanzu** [comment]
Closing this issue for now as the sounds are removed now (will be added again in the future)
And The rendering should be different now.
Feel free to re-open if the issue still persists :)
