### ISSUE TITLE
Don't highlight the current typing letter and add " | " cursor style💡 [FEAT]

### ISSUE THREAD

**Issue by bickman** [kraanzu/smassh#40]
There is no need to highlight current typing letter , it may cause distraction or just add this option  and  please add  " | "  cursor style as `monkeytype`  shown below :

![monkeytype](https://user-images.githubusercontent.com/11661626/181504769-eccbb37f-1b00-4b56-a926-950de8623346.png)

**Comment by bickman** [comment]
> The cursor moves in between the characters but the | won't... It takes up a whole space of a character

I know there may be some technical difficulty for using " | " cursor without taking up a space of a character in a tui. However, just like the " _ " underline cursor using here , it doesn't takes up a space. I am sure you can make it perfectly.

**Comment by kraanzu** [comment]
Hey. I checked a lot but this isn't supported by the underlying TUI library being used
So I'll have to close this one. Feel free to open any other issues you might have :smile:
