### ISSUE TITLE
💡 [FEAT] Full XDG compliance

### ISSUE THREAD

**Issue by TheSast** [kraanzu/smassh#48]
**Is your feature request related to a problem? 😢 Please describe.** 
termtyper does not fully respect the XDG Base Directory Specification.

**Describe the solution you'd like**   🤔
Store the `[speed records word]` and `[speed records time]` sections of `$XDG_CONFIG_HOME/termtyper/termtyper.ini` in `$XDG_DATA_HOME/termtyper/termtyper.ini`

**Comment by kraanzu** [comment]
Hey @TheSast , thanks for opening an issue. I'm actually in the process of making a lot of changes and will be adding this as well :)

**Comment by kraanzu** [comment]
All the config files should be now in the proper locations!

You can verify this by running these commands:

```bash
python -c "import appdirs; print(appdirs.user_config_dir('smassh'))"
```

```bash
python -c "import appdirs; print(appdirs.user_data_dir('smassh'))"
```
