### ISSUE TITLE
New languages

### ISSUE THREAD

**Issue by zotic1001** [kraanzu/smassh#52]
It might be worth adding other languages to practice typing, such as Russian or German.  In the code of the generator function, you can add a language selection. Accordingly, add language selection and progress regardless of languages to the menu.

**Comment by kraanzu** [comment]
Closing this as this is now supported!
See [Wiki](https://github.com/kraanzu/smassh/wiki/Add-Languages)

![image](https://github.com/kraanzu/smassh/assets/97718086/4707201d-7e33-4eb3-b541-d3ec98223e0c)

You can press `ctrl+l` or click on the language to select language
