### ISSUE TITLE
[BUG] Hitting backspace multiple times does not delete characters

### ISSUE THREAD

**Issue by DylanHojnoski** [kraanzu/smassh#65]
### Describe the bug 🐛

When you hit the backspace the first time it deletes the character but if you hit it multiple times it only moves the cursor without deleting the characters. This results in the cursor being behind the typed text and when you try to finish a word count type test it crashes with an index out of bounds error.

### To Reproduce 🐣

1. open the program
2. set to words mode
3. start typing
4. hit backspace a few of time
5. continue typing until you complete it

### Expected behavior 🤔

The characters should be deleted when you hit backspace not just move the cursor.

### Screenshots 🧐

![20240204_11h10m58s_grim](https://github.com/kraanzu/smassh/assets/68570349/9963feaa-8ac1-4be1-a269-4fc5c4c4be3f)

![20240204_11h12m16s_grim](https://github.com/kraanzu/smassh/assets/68570349/2333d22c-3df5-42be-984b-410ecf749a02)

### Your operating system name

Linux

### Your operating system version

Fedora 38

**Comment by feschber** [comment]
#64

**Comment by kraanzu** [comment]
Hey I've pushed a fix! Can you quickly do install and recheck ? :)

**Comment by kraanzu** [comment]
I'll close this issue as this is fixed now.
Feel free to re-open if the issue still persists :D
