### ISSUE TITLE
[BUG] Can't change settings

### ISSUE THREAD

**Issue by NextStep-IM** [kraanzu/smassh#67]
### Describe the bug 🐛

I can't change difficulty. It's stuck on normal. Same for other settings.

### To Reproduce 🐣

1. Start _smassh_
2. Go to _settings_
3. Click on any option to change a setting.

### Expected behavior 🤔

Clicking on the buttons should make the values change.

### Screenshots 🧐

[recording.webm](https://github.com/kraanzu/smassh/assets/140648058/89c2e6eb-27ed-4c10-8bfa-856049801205)

### Your operating system name

Arco Linux 

### Your operating system version

6.7.3-arch1-1 

### Additional context 📝

I installed using _pipx_.

**Comment by kraanzu** [comment]
Hey @NextStep-IM ,

Oopsies. Those were meant to only be changed via `tab` and `shift-tab` but I guess if it highlights on hover, It should work with a click too. I'll add that :)

**Comment by NextStep-IM** [comment]
Damn that was fast. Thanks a lot, @kraanzu!
