### ISSUE TITLE
Alt+backspace at start of test throws error [BUG]

### ISSUE THREAD

**Issue by Narmis-E** [kraanzu/smassh#70]
### Describe the bug 🐛

Using alt+backspace to remove an entire word when there are no letters typed throws an index error and quits the program.

### To Reproduce 🐣

1. start _smassh_
2. alt+backspace

### Expected behavior 🤔

Nothing should happen if there are no letters or words that have been written. 

### Screenshots 🧐

![image](https://github.com/kraanzu/smassh/assets/109248529/a5b74b0b-c9d5-4d38-ba3c-66f95be359e0)

### Your operating system name

Arch Linux

### Your operating system version

6.7.3-arch1-1

### Additional context 📝

Using kitty inside a tmux session (same thing happens without tmux however). I cant offer much help with my (lack of) expertise in python but is the `correct=<Match.BACKSPACE: 3>` part of the checkpoint trying to remove up until a third letter when there are none? This isn't a big issue as nobody needs to backspace at the start, but just thought I'd let you know.

Installed via AUR.

EDIT: I just noticed you made a fix for using ctrl+w which had the same issue, is this something similar?

**Comment by kraanzu** [comment]
> EDIT: I just noticed you made a fix for using ctrl+w which had the same issue, is this something similar?

Yes, I just need to make a quick hotfix release. Lemme do that
