### ISSUE TITLE
💡 [FEAT] Add a 2 second delay before ending the test due to min setting restriction

### ISSUE THREAD

**Issue by kraanzu** [kraanzu/smassh#75]
### Is your feature request related to a problem? 😢 Please describe.

Typing test ends because of the first three settings #74 

### Describe the solution you'd like 🤔

We should wait for like ~2s before ending the test because the calculation for the first few keystrokes is highly variable 

### Describe alternatives you've considered 🧐

Deleting the app

**Comment by frizd** [comment]
Closing as it is fixed in PR #80
