### ISSUE TITLE
[BUG] Crashes when the "cursor buddy" beats you...

### ISSUE THREAD

**Issue by samuelj123** [kraanzu/smassh#78]
### Describe the bug 🐛

If the "cursor buddy" finishes the typing before I do, it crashes and throws up a whole bunch of errors. 

### To Reproduce 🐣

0. Get on Ubuntu on WSL, install smassh using pip
1. Go to "settings", find "cursor buddy" pull his speed to 50. (or more, if you're faster than me)
2. Race against the cursor, Lose.

### Expected behavior 🤔

It crashes... 

### Screenshots 🧐

<img width="960" alt="image" src="https://github.com/kraanzu/smassh/assets/28726139/9208cddf-786e-4dff-92f8-6aa765647329">

### Your operating system name

Ubuntu on WSL

**Comment by kraanzu** [comment]
Damn.. Cursor buddy be doing some real damage there lol
I'm a little busy now. I'll push a fix tomm morning :)

Thanks for trying out Smassh <3

**Comment by kraanzu** [comment]
Hey @samuelj123, I cannot reproduce this behavior (although cursor buddy vanishes) for both time and word mode.
Can you share your config file with me?

```bash
python -c "import appdirs; print(appdirs.user_data_dir('smassh'))"
```

You can run the above command to get the location of the config dir. Inside which, will be a file called `smassh.json`

**Comment by frizd** [comment]
Just adding to avoid any confusion, the commit (before my comment), doesn't fixes this issue, I mistakenly wrote 78 instead of 75

**Comment by samuelj123** [comment]
Sorry for the delay...
Here's the contents of smassh.json 

```json
{
  "data": [
    {
      "mode": "words",
      "count": 30,
      "start_time": 1707189131.3083422,
      "elapsed_time": 23.058086156845093,
      "wpm": 75,
      "raw_wpm": 75,
      "accuracy": 100,
      "failed": false
    },
    {
      "mode": "words",
      "count": 30,
      "start_time": 1707189241.9093516,
      "elapsed_time": 23.416937112808228,
      "wpm": 13,
      "raw_wpm": 74,
      "accuracy": 18,
      "failed": false
    },
    {
      "mode": "words",
      "count": 30,
      "start_time": 1707189586.3821304,
      "elapsed_time": 22.5915789604187,
      "wpm": 74,
      "raw_wpm": 77,
      "accuracy": 96,
      "failed": false
    },
    {
      "mode": "words",
      "count": 30,
      "start_time": 1707190641.2839632,
      "elapsed_time": 24.710692167282104,
      "wpm": 69,
      "raw_wpm": 70,
      "accuracy": 98,
      "failed": false
    }
  ]
}

```

**Comment by kraanzu** [comment]
Hey @samuelj123! My comment was incorrect. I update the command :)

**Comment by samuelj123** [comment]
Hey @kraanzu , so technically all I need to do is just run `pip install --upgrade smassh` for it to work right? Or should I wait for 3.2.0 to be available on pip? I right now seem to have 3.0.4 ... Sorry! New to all this

**Comment by kraanzu** [comment]
Ah no I meant the command in the previous comment I made. The text file which you just share is the log data and not the config
Here's how you can get the config:

```
python -c "import appdirs; print(appdirs.user_config_dir('smassh'))"
```

**Comment by samuelj123** [comment]
Ah! Right
```json
{
  "difficulty": "normal",
  "blind_mode": false,
  "min_speed": 0,
  "min_accuracy": 0,
  "min_burst": 0,
  "force_correct": false,
  "confidence_mode": "off",
  "capitalization_mode": "off",
  "cursor_buddy_speed": 30,
  "tab_reset": "on",
  "language": "english",
  "numbers": false,
  "punctuations": false,
  "mode": "words",
  "words_count": 30,
  "time_count": 30,
  "caret_style": "block",
  "writing mode": "words",
  "theme": "dracula"
}
```

**Comment by kraanzu** [comment]
Awesome! I'll check it out

**Comment by samuelj123** [comment]
Yep!! All fixed! Starring away
