### ISSUE TITLE
[BUG] no indication when I mistype a space

### ISSUE THREAD

**Issue by rhuygen** [kraanzu/smassh#90]
### Describe the bug 🐛

When I should type a space but by mistake type another character, I see no error, and a space is printed anyway. I think this should be considered as an error and maybe a red underscore should be printed to indicate the error.

### To Reproduce 🐣

1. Start a test by typing the letters
2. type another character when a space should be typed

### Expected behavior 🤔

I would expect an indication that a wrong character was typed. Perhaps an red underscore could be used for this.

### Your operating system name

macOS

### Your operating system version

Sonoma 14.5

### Additional context 📝

I'm using iTerm2.

**Comment by kraanzu** [comment]
Hi @rhuygen !

True, this will indeed confuse the user if they see all green letters but accuracy is not 100%

I'm trying to think about the possibilities here, i.e. the character to use

![image](https://github.com/user-attachments/assets/2a99ed41-4b76-4170-aea3-d15717c26612)

![image](https://github.com/user-attachments/assets/1b5283a2-1877-4237-82e6-0e615bb9880e)


I have these two options here. Personally, I liked the former. What do you think?

**Comment by rhuygen** [comment]
Hi, I’m happy with both of them, if users have different preferences, you could make it a config item.

**Comment by kraanzu** [comment]
Hmmm... I don't want to populate the settings with unnecessary ones
I guess I'll merge this and add a setting in the future if someone  wants it
