### ISSUE TITLE
[BUG] Cannot change language or theme in the TUI

### ISSUE THREAD

**Issue by jaxvanyang** [kraanzu/smassh#92]
### Describe the bug 🐛

It seems like that the textual API change breaks this function.

### To Reproduce 🐣

1. Start smassh
2. Click the bottom language or theme
3. Crash

### Screenshots 🧐

![image](https://github.com/user-attachments/assets/199d2981-c616-4737-9bd2-07ab678b686c)

### Your operating system name

Arch Linux

### Additional context 📝

#91

**Comment by kraanzu** [comment]
Oh boy, and here I thought I only needed to update a few things only
